### ISSUE TITLE
Investigate if we can use a commit hook to update version on master

### ISSUE THREAD

**Issue by drBosse** [Praqma/toggleR#15]

**Comment by drBosse** [comment]
R is using the archaic solution to keep the package version in the `DESCRIPTION` file

Releases use 3 digits, `x.y.z` and developer versions adds a `.buildnumber`

As an initial workaround in the Jenkinsfile, the version string is replaced with a string derived from `git describe` . E.g. 1.2.3-4-g<SHA1> => 1.2.3.4

This (sort of) works:
- downloading from jenkins or releases from github will show that version when loaded
- installing from github or local builds will however show the initial `0.0.0.9000`
- there might be many 1.2.3.4 versions, any branch that have 4 commits since the 1.2.3-tag will have the same version

My first thought was git hooks.......but not so sure 

Maybe we have to use release branches ........like

When we tag master, we update description with <tag>.9000 the branch out from tag and remove the 9000 and release that


Feels like I am running out of good ideas

@kvarak and @JKrag need some thoughtful input here

**Comment by kvarak** [comment]
Not sure if thoughtful input is the thing you'll get, but here are a couple of cents.

I'm not really fond of requiring commit hooks for the release process, because they aren't in the repo and it's hard to give them to everyone that will contribute. Also, if you by chance re-clone the repo, you need to remember to add the commit hook.

Maybe, if you combine that with a pre-receive hook on GitHub that checks if you've updated the version (regardless if it's done by a commit hook or manually)... but, I don't know about this...

> installing from github or local builds will however show the initial 0.0.0.9000

Does it matter in this case? If somebody installs from non-release or local build, then they (hopefully) know what they are doing?

> there might be many 1.2.3.4 versions, any branch that have 4 commits since the 1.2.3-tag will have the same version

Is it possible to add the branch name to the version or is it always 4 numbers? But also, we're not releasing from non-master, so

---

Couldn't always using ready/* branches be (part of) a solution here? I mean, editing the `DESCRIPTION` file could be done in the first merge before build and test.

---

On another note, If the versions are semantic versions (I think they are, but only manually so?), maybe we should try to use PlusBump? (You know, eat our own dogfood and that. Also give Jan and Mads an incentive to keep it updated/growing).

I have no idea, but maybe parts of the problems you're describing has been solved by PlusBump?
